/** Canonical immutable document types shared by runtime and wire integrations. */
export type {
  AthleteProfile,
  CapabilityObservation,
  CompletedExercise,
  CompletedSet,
  CompletedWorkout,
  EvaluationRequest,
  EvaluationResult,
  EquipmentDelta,
  EquipmentRequirement,
  Exercise,
  ExerciseFatigue,
  ExerciseKnowledge,
  ExercisePreference,
  ExerciseRelationships,
  ExerciseVariantDimension,
  JsonObject,
  JsonValue,
  KnowledgeAuthority,
  KnowledgeConfidence,
  KnowledgeEvidence,
  Measurement,
  MusclePriority,
  MethodologyRef,
  MethodologyState,
  Metric,
  ProgressionCapabilities,
  RecommendationRequest,
  RecommendationResult,
  ResolvedTrainingContext,
  TrainingContext,
  TrainingLocation,
  TrainingRestriction,
  TrackingDimension,
  TrackingSnapshot,
} from "./index.ts";
