const std = @import("std");

pub const CompletionShell = enum { bash, zsh, fish };

const Command = struct {
    name: []const u8,
    usage: []const u8,
    summary: []const u8,
};

const commands = [_]Command{
    .{ .name = "database", .usage = "database info|check", .summary = "Show public adapter metadata or a sanitized integrity result." },
    .{ .name = "doctor", .usage = "doctor", .summary = "Run the same sanitized database integrity check." },
    .{ .name = "workout", .usage = "workout start|add-exercise|show|finish|cancel", .summary = "Start, modify, inspect, finish, or cancel workouts." },
    .{ .name = "set", .usage = "set log|skip|reopen", .summary = "Record or adjust a workout set." },
    .{ .name = "exercise", .usage = "exercise create|edit|show|list|search|archive|restore", .summary = "Manage the local exercise catalog." },
    .{ .name = "history", .usage = "history list|show|exercise|last|correct-set", .summary = "Inspect completed workouts and correct logged sets." },
    .{ .name = "config", .usage = "config path|show|set", .summary = "Inspect or change client-only presentation preferences." },
    .{ .name = "batch", .usage = "batch FILE", .summary = "Run bounded JSON Lines automation input." },
    .{ .name = "completion", .usage = "completion bash|zsh|fish", .summary = "Print a shell completion script without opening a database." },
    .{ .name = "command-reference", .usage = "command-reference", .summary = "Print this generated Markdown command reference." },
};

pub fn parseCompletionShell(value: []const u8) ?CompletionShell {
    if (std.mem.eql(u8, value, "bash")) return .bash;
    if (std.mem.eql(u8, value, "zsh")) return .zsh;
    if (std.mem.eql(u8, value, "fish")) return .fish;
    return null;
}

pub fn writeCompletion(writer: *std.Io.Writer, shell: CompletionShell) !void {
    switch (shell) {
        .bash => {
            try writer.writeAll("# bash completion for caudex\n_caudex() {\n    local commands=\"");
            try writeNames(writer, " ");
            try writer.writeAll("\"\n    COMPREPLY=( $(compgen -W \"$commands\" -- \"${COMP_WORDS[COMP_CWORD]}\") )\n}\ncomplete -F _caudex caudex\n");
        },
        .zsh => {
            try writer.writeAll("#compdef caudex\n_arguments '1:command:(");
            try writeNames(writer, " ");
            try writer.writeAll(")'\n");
        },
        .fish => {
            for (commands) |command|
                try writer.print("complete -c caudex -f -a '{s}'\n", .{command.name});
        },
    }
}

pub fn writeReference(writer: *std.Io.Writer) !void {
    try writer.writeAll("# Caudex CLI command reference\n\nGenerated by `caudex command-reference` from the client command metadata.\n\n");
    for (commands) |command|
        try writer.print("## `{s}`\n\n`caudex {s}`\n\n{s}\n\n", .{ command.name, command.usage, command.summary });
}

fn writeNames(writer: *std.Io.Writer, separator: []const u8) !void {
    for (commands, 0..) |command, index| {
        if (index != 0) try writer.writeAll(separator);
        try writer.writeAll(command.name);
    }
}
